### ISSUE TITLE
how to output chinese discription?

### ISSUE THREAD

**Issue by dongdk** [steven640pixel/GalleryGPT#6]
i use chinese query e.g. `请对这幅画的构图进行分析` as the paper does, but the model generates the english description. so how to let the model ouputs corresponding chinese description?

**Comment by steven640pixel** [comment]
You might try ‘请用中文对这幅画的构图进行分析。’  to let the model ouputs corresponding chinese description.

**Comment by dongdk** [comment]
get it. i will try it later

**Comment by dongdk** [comment]
yeah, it works. btw, is it that when finetune the model, the dataset contains chinese instructions?

**Comment by steven640pixel** [comment]
The dataset for fine-tuning only contains English instructions. Possibly the base model Sharegpt4v has some bilingual ability and has learnt to write art formal analysis through sft.

**Comment by dongdk** [comment]
ok, i will close the issue
